---
title: "Lab 7: Group 03"
format: html
editor: visual
---

### Group members:

s225049: Ida Sofie Goldschmidt\
s225074: Annekatrine Kirketerp-Møller\
s225051: Emil August Dissing Berntsen\
s224974: Rasmus Kamp\
s215109: Rolf Larsen

## Load libraries

```{r}
#| message: false

library("tidyverse")
library("broom")
library("cowplot")
library("ggrepel")

```

## Loading and tidying data:

```{r}
#| message: false

biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE) 
```

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |>
  scale() |> 
  prcomp() 
```

```{r}
pca_fit |>
  augment(biopsy) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, 
             color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "hotpink", 
               benign = "forestgreen")) +
  theme_half_open(12) + background_grid()
```

```{r}
# extract rotation matrix
pca_fit |>
  tidy(matrix = "rotation")
```

```{r}
# define arrow style for plotting
arrow_style <- arrow(
                angle = 20, 
                ends = "first", 
                type = "closed", 
                length = grid::unit(8, "pt"))

# plot rotation matrix
pca_fit |>
  tidy(matrix = "rotation") |>
  pivot_wider(names_from = "PC", 
              names_prefix = "PC", 
              values_from = "value") |>
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, 
               yend = 0, 
               arrow = arrow_style) +
  geom_text_repel(
    aes(label = column),
    color = "cornflowerblue") +
  
  xlim(-.7, .05) + 
  ylim(-.4, 1) +
  theme_minimal_grid(12)
```

```{r}
pca_fit |>
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit |>
  tidy(matrix = "eigenvalues") |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "orange2", 
           alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```
